# House Price Prediction System
## Exploratory Data Analysis
### Objectives
- Understand the dataset
- Analyze the features
- Identify missing values
- Explore relationships between variables
- Prepare the data for preprocessing

## 1. Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import sys
import subprocess
import importlib
import pandas as pd
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)
print("Libraries imported successfully.")

Libraries imported successfully.

## 2. Load Dataset

In [2]:
df = pd.read_csv("../data/Housing.csv")
df.head()

,Id,LotArea,OverallQual,OverallCond,YearBuilt,TotalBsmtSF,GrLivArea,FullBath,BedroomAbvGr,KitchenAbvGr,SalePrice
0,1,8450,7,5,2003,856,1710,2,3,1,208500

## 3. Dataset Overview

In [3]:
df.shape

(1, 11)

In [4]:
df.columns

Index(['Id', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt',
       'TotalBsmtSF', 'GrLivArea', 'FullBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'SalePrice'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            1 non-null      int64
 1   LotArea       1 non-null      int64
 2   OverallQual   1 non-null      int64
 3   OverallCond   1 non-null      int64
 4   YearBuilt     1 non-null      int64
 5   TotalBsmtSF   1 non-null      int64
 6   GrLivArea     1 non-null      int64
 7   FullBath      1 non-null      int64
 8   BedroomAbvGr  1 non-null      int64
 9   KitchenAbvGr  1 non-null      int64
 10  SalePrice     1 non-null      int64
dtypes: int64(11)
memory usage: 220.0 bytes

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Id,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0
LotArea,1.0,8450.0,NaN,8450.0,8450.0,8450.0,8450.0,8450.0
OverallQual,1.0,7.0,NaN,7.0,7.0,7.0,7.0,7.0
OverallCond,1.0,5.0,NaN,5.0,5.0,5.0,5.0,5.0
YearBuilt,1.0,2003.0,NaN,2003.0,2003.0,2003.0,2003.0,2003.0
TotalBsmtSF,1.0,856.0,NaN,856.0,856.0,856.0,856.0,856.0
GrLivArea,1.0,1710.0,NaN,1710.0,1710.0,1710.0,1710.0,1710.0
FullBath,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0
BedroomAbvGr,1.0,3.0,NaN,3.0,3.0,3.0,3.0,3.0
KitchenAbvGr,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0
SalePrice,1.0,208500.0,NaN,208500.0,208500.0,208500.0,208500.0,208500.0

In [7]:
df.isnull().sum()

Id              0
LotArea         0
OverallQual     0
OverallCond     0
YearBuilt       0
TotalBsmtSF     0
GrLivArea       0
FullBath        0
BedroomAbvGr    0
KitchenAbvGr    0
SalePrice       0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df.head()

,Id,LotArea,OverallQual,OverallCond,YearBuilt,TotalBsmtSF,GrLivArea,FullBath,BedroomAbvGr,KitchenAbvGr,SalePrice
0,1,8450,7,5,2003,856,1710,2,3,1,208500