# House Price Prediction System

# Data Preprocessing

## Objectives

- Handle missing values
- Encode categorical variables
- Prepare features and target
- Split the dataset for training and testing

## 1. Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

## 2. Load Dataset

In [2]:
df = pd.read_csv("../data/Housing.csv")

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

## 3. Check Missing Values

In [3]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

## 4. Encode Yes/No Columns

In [4]:
yes_no_columns = [
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea"
]

for column in yes_no_columns:
    df[column] = df[column].map({
        "yes": 1,
        "no": 0
    })

## 5. Encode Furnishing Status

In [5]:
df["furnishingstatus"] = df["furnishingstatus"].map({
    "furnished": 2,
    "semi-furnished": 1,
    "unfurnished": 0
})

In [6]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,2
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,2
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,2
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,2

## 6. Separate Features and Target

In [7]:
X = df.drop("price", axis=1)

y = df["price"]

In [8]:
print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (545, 12)
Target Shape : (545,)

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

## 7. Train-Test Split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
print("Training Data :", X_train.shape)
print("Testing Data :", X_test.shape)

Training Data : (436, 12)
Testing Data : (109, 12)

# Preprocessing Summary

- Checked missing values
- Encoded categorical variables
- Prepared feature matrix
- Prepared target variable
- Split the dataset into training and testing sets